# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 21:31
from __future__ import unicode_literals

import Clothes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=140)),
                ('Description', models.TextField()),
                ('DateTime_Posted', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(upload_to='')),
                ('User', models.ForeignKey(on_delete=models.SET(Clothes.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
