# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing_post',
            name='Bought',
            field=models.BooleanField(default=False),
        ),
    ]
