# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0002_clothing_post_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing_post',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=100.99, max_digits=6),
            preserve_default=False,
        ),
    ]
