# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 22:14
from __future__ import unicode_literals

import Clothes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clothes', '0004_auto_20171021_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=models.SET(Clothes.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart_item',
            name='Cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clothes.User_Cart'),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='Clothing_Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clothes.Clothing_Post'),
        ),
    ]
