# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clothes', '0006_user_cart_paypal_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_cart',
            unique_together=set([('User', 'Paypal_Account')]),
        ),
    ]
