# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Item',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='Clothes.Clothing_Post'),
            preserve_default=False,
        ),
    ]
