# Generated by Django 2.0 on 2018-01-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0003_auto_20171225_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Shipping_Reciept',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
