# Generated by Django 2.0 on 2018-01-05 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0004_transaction_shipping_reciept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Shipping_Reciept',
            new_name='Shipping_Receipt',
        ),
    ]
