# Generated by Django 2.0 on 2018-01-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0005_auto_20180105_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Viewing_Buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Viewing_Seller',
            field=models.BooleanField(default=False),
        ),
    ]
