# Generated by Django 2.0 on 2018-04-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0009_auto_20180401_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Completed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='PP_Id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Viewing_Buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Viewing_Seller',
        ),
    ]
