# Generated by Django 2.0 on 2018-04-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0010_auto_20180408_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Complete',
            field=models.BooleanField(default=False),
        ),
    ]
