# Generated by Django 2.0 on 2018-04-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0011_transaction_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='Size',
            field=models.CharField(default='M', max_length=3),
            preserve_default=False,
        ),
    ]
