# Generated by Django 2.0 on 2018-04-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0012_auto_20180411_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Likes',
        ),
        migrations.AddField(
            model_name='product',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Size',
            field=models.CharField(max_length=50),
        ),
    ]
