# Generated by Django 2.0 on 2018-07-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0013_auto_20180420_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Likes',
            new_name='Votes',
        ),
    ]
