# Generated by Django 2.0 on 2018-07-04 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0015_auto_20180704_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_Bought',
            new_name='Bought',
        ),
    ]
